rent = float(input('Rent per month: '))
gas = float(input('Gas payment per month: '))
electricity = float(input('Electricity payment per month: '))
water = float(input('Water payment per month: '))
council_tax = float(input('Council tax payment per month: '))
total_payment = rent + gas + electricity + water + council_tax 
print('Your monthly expenses are:')
print('Rent:          $   ' + format(rent,'.2f'))
print('Gas:           $   ' + format(gas,'.2f'))
print('Electricity:   $   ' + format(electricity,'.2f'))
print('Water:         $   ' + format(water,'.2f'))
print('Council Tax:   $   ' + format(council_tax,'.2f'))
print('========================')
print('Total:         $   ' + format(total_payment,'.2f'))
print('========================')
